spring:
  profiles:
    active: dev

---
spring:
  mail:
    host: smtp.qq.com
    username: 3468793275@qq.com
    password: msaimrojwynlchbb
    default-encoding: utf-8
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    username: guest
    password: guest
    host: 47.95.241.173
    port: 5672
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update，要不然每次重启都会新建表
    show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000ms
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/join?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong&allowMultiQueries=true
    username: root
    password: system
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 100000
      web-stat-filter.enabled: true
      web-stat-filter.url-pattern: /*
      web-stat-filter.exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet.enabled:  true
      stat-view-servlet.url-pattern: /druid/*
      stat-view-servlet.reset-enable: false
      stat-view-servlet.login-username: admin
      stat-view-servlet.login-password: admin
      stat-view-servlet.allow: 127.0.0.1
      ###监控配置 end###

      # 配置StatFilter
      filter.stat.db-type: mysql
      filter.stat.log-slow-sql: true
      filter.stat.slow-sql-millis: 5000

      # 配置WallFilter
      filter.wall.enabled: true
      filter.wall.db-type: mysql
      filter.wall.config.delete-allow: false
      filter.wall.config.drop-table-allow: false
server:
  port: 8888
mybatis:
  config-location: classpath:mybatis/configuration.xml
logging:
  level:
    com.matrix.join.dao : debug

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.matrix.join.po
  typeEnumsPackage: com.matrix.join.common